import './globals.css'
import type { Metadata } from 'next'
import Header from '@/components/header/Header'
import Footer from '@/components/footer'
import Theme from '@/providers/theme'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body>
        <Theme>
          <Header></Header>
          {children}
          <Footer></Footer>
        </Theme>
      </body>
    </html>
  )
}
